#pragma once

#include <stdint.h>

enum class Format : uint16_t {
    NONE,

    R8_UNORM, R8_UINT, R8_SRGB,

    RG8_UNORM, RG8_UINT, RG8_SRGB,

    RGBA8_UNORM, RGBA8_UINT, RGBA8_SRGB,
    BGRA8_UNORM, BGRA8_UINT, BGRA8_SRGB,

    R16_UNORM, R16_UINT, R16_FLOAT,

    RG16_UNORM, RG16_UINT, RG16_FLOAT,

    RGBA16_UNORM, RGBA16_UINT, RGBA16_FLOAT,

    R32_UINT, R32_FLOAT,

    RG32_UINT, RG32_FLOAT,

    RGB32_UINT, RGB32_FLOAT,

    RGBA32_UINT, RGBA32_FLOAT,

    RGB10A2_UNORM, RGB10A2_UINT, RG11B10_UFLOAT,

    BC7_4x4_UNORM, BC7_4x4_SRGB,

    D16_UNORM, D24_UNORM_S8_UINT, D32_FLOAT,

    COUNT
};

enum class Filter : uint8_t { POINT, BILINEAR, TRILINEAR, COUNT};
enum class WrapMode : uint16_t { WRAP, CLAMP_TO_EDGE, CLAMP_TO_BORDER, COUNT };
enum class CullMode : uint16_t { NONE, CCW, CW, COUNT };